#!/usr/bin/env bash
# This script configures host resolution for localhost and facebook.com

# /etc/hosts faylındakı köhnə 127.0.0.1-i rəsmən 127.0.0.2 ilə əvəzləyirik
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Əgər facebook.com faylda yoxdursa, onu da sonuna rəsmən əlavə edirik
if ! grep -q "facebook.com" /etc/hosts; then
    echo "8.8.8.8 facebook.com" >> /etc/hosts
else
    sed -i 's/.*facebook.com/8.8.8.8 facebook.com/g' /etc/hosts
fi
