#!/usr/bin/env bash
# This script configures host resolution for localhost and facebook.com
sudo sh -c 'echo "127.0.0.2 localhost" >> /etc/hosts'
sudo sh -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'
