#!/usr/bin/env bash
# This script displays active IPv4 addresses using standard networking tools
if command -v ifconfig &> /dev/null; then
    ifconfig | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
else
    ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
fi
