#!/usr/bin/env bash
# This script displays the machine's active network interfaces reliably
if command -v ifconfig &> /dev/null; then
    ifconfig -a | grep -E '^[a-zA-Z0-9]' | cut -d: -f1 | cut -d' ' -f1
else
    ip -o link show | awk -F': ' '{print $2}'
fi
